In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("hw7.ipynb")

# CPSC 330 - Applied Machine Learning 

## Homework 7: Word embeddings and topic modeling 

**Due date: See [deliverable due dates](https://ubc-cs.github.io/cpsc330-2025W2/#deliverable-due-dates-tentative)**.

## Imports

In [2]:
import os

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, make_pipeline

<br><br>

<!-- BEGIN QUESTION -->

<!-- BEGIN QUESTION -->

<div class="alert alert-info">
    
## Instructions
rubric={points}

You will earn points for following these instructions and successfully submitting your work on Gradescope.  

### Group wotk instructions

**You may work with a partner on this homework and submit your assignment as a group.** Below are some instructions on working as a group.  
- The maximum group size is 2.
  
- Use group work as an opportunity to collaborate and learn new things from each other. 
- Be respectful to each other and make sure you understand all the concepts in the assignment well. 
- It's your responsibility to make sure that the assignment is submitted by one of the group members before the deadline. 
- You can find the instructions on how to do group submission on Gradescope [here](https://help.gradescope.com/article/m5qz2xsnjy-student-add-group-members).
- If you would like to use late tokens for the homework, all group members must have the necessary late tokens available. Please note that the late tokens will be counted for all members of the group.   


### General submission instructions

- Please **read carefully
[Use of Generative AI policy](https://ubc-cs.github.io/cpsc330-2025W2/syllabus#use-of-generative-ai-in-the-course)** before starting the homework assignment. 
- **Run all cells before submitting:** Go to `Kernel -> Restart Kernel and Clear All Outputs`, then select `Run -> Run All Cells`. This ensures your notebook runs cleanly from start to finish without errors.
  
- **Submit your files on Gradescope.**  
   - Upload only your `.ipynb` file **with outputs displayed** and any required output files.
     
   - Do **not** submit other files from your repository.  
   - If you need help, see the [Gradescope Student Guide](https://lthub.ubc.ca/guides/gradescope-student-guide/).  
- **Check that outputs render properly.**  
   - Make sure all plots and outputs appear in your submission.
     
   - If your `.ipynb` file is too large and doesn't render on Gradescope, also upload a PDF or HTML version so the TAs can view your work.  
- **Keep execution order clean.**  
   - Execution numbers must start at "1" and increase in order.
     
   - Notebooks without visible outputs may not be graded.  
   - Out-of-order or missing execution numbers may result in mark deductions.  
- **Follow course submission guidelines:** Review the [CPSC 330 homework instructions](https://ubc-cs.github.io/cpsc330-2025W2/docs/homework-instructions) for detailed guidance on completing and submitting assignments. 
   
</div>


_Points:_ 2

<!-- END QUESTION -->

<br><br><br><br>

## Exercise 1:  Exploring pre-trained word embeddings <a name="1"></a>
<hr>

In lecture 18, we talked about natural language processing (NLP). Using pre-trained word embeddings is very common in NLP. It has been shown that pre-trained word embeddings work well on a variety of text classification tasks. These embeddings are created by training a model like Word2Vec on a huge corpus of text such as a dump of Wikipedia or a dump of the web crawl. 

A number of pre-trained word embeddings are available out there. Some popular ones are: 

- [GloVe](https://nlp.stanford.edu/projects/glove/)
    * trained using [the GloVe algorithm](https://nlp.stanford.edu/pubs/glove.pdf) 
    * published by Stanford University 
- [fastText pre-trained embeddings for 294 languages](https://fasttext.cc/docs/en/pretrained-vectors.html) 
    * trained using the fastText algorithm
    * published by Facebook
    
In this exercise, you will be exploring GloVe Wikipedia pre-trained embeddings. The code below loads the word vectors trained on Wikipedia using an algorithm called Glove. You'll need `gensim` package in your cpsc330 conda environment to run the code below. 

```
> conda activate cpsc330
> conda install -c anaconda gensim
```

In [3]:
import gensim
import gensim.downloader

print(list(gensim.downloader.info()["models"].keys()))

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']

In [4]:
# This will take a while to run when you run it for the first time.
import gensim.downloader as api

glove_wiki_vectors = api.load("glove-wiki-gigaword-100")

In [5]:
len(glove_wiki_vectors)

400000

There are 400,000 word vectors in this pre-trained model.

Now that we have GloVe Wiki vectors loaded in `glove_wiki_vectors`, let's explore the embeddings.

<br><br>

<!-- BEGIN QUESTION -->

### 1.1 Word similarity using pre-trained embeddings
rubric={points}

**Your tasks:**

- Come up with a list of 4 words of your choice and find similar words to these words using `glove_wiki_vectors` embeddings.

<div class="alert alert-warning">

Solution_1.1
    
</div>

_Points:_ 2

In [6]:
words = ["sneakers", "volleyball", "wine", "league"]

In [7]:
for word in words:
    print(f"Words similar to '{word}':")
    similar_words = glove_wiki_vectors.most_similar(word, topn=5)
    for sim_word, score in similar_words:
        print(f" - {sim_word} ({score:.4f})")

Words similar to 'sneakers':
 - shoes (0.8316)
 - jeans (0.7956)
 - socks (0.7707)
 - pants (0.7514)
 - underwear (0.7394)
Words similar to 'volleyball':
 - softball (0.8331)
 - badminton (0.8076)
 - handball (0.7868)
 - soccer (0.7690)
 - gymnastics (0.7622)
Words similar to 'wine':
 - wines (0.8375)
 - tasting (0.7492)
 - beer (0.7245)
 - grape (0.7133)
 - champagne (0.7055)
Words similar to 'league':
 - football (0.8153)
 - club (0.7835)
 - leagues (0.7801)
 - teams (0.7502)
 - team (0.7445)

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 1.2 Word similarity using pre-trained embeddings
rubric={points}

**Your tasks:**

1. Calculate cosine similarity for the following word pairs (`word_pairs`) using the [`similarity`](https://radimrehurek.com/gensim/models/keyedvectors.html?highlight=similarity#gensim.models.keyedvectors.KeyedVectors.similarity) method of `glove_wiki_vectors`.

In [8]:
word_pairs = [
    ("coast", "shore"),
    ("clothes", "closet"),
    ("old", "new"),
    ("smart", "intelligent"),
    ("dog", "cat"),
    ("tree", "lawyer"),
]

<div class="alert alert-warning">

Solution_1.2
    
</div>

_Points:_ 2

In [9]:
for pair in word_pairs:
    similarity_score = glove_wiki_vectors.similarity(pair[0], pair[1])
    print(f"Similarity between '{pair[0]}' and '{pair[1]}': {similarity_score:.4f}")

Similarity between 'coast' and 'shore': 0.7000
Similarity between 'clothes' and 'closet': 0.5463
Similarity between 'old' and 'new': 0.6432
Similarity between 'smart' and 'intelligent': 0.7553
Similarity between 'dog' and 'cat': 0.8798
Similarity between 'tree' and 'lawyer': 0.0767

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 1.3 Representation of all words in English
rubric={points}

**Your tasks:**

1. The vocabulary size of Wikipedia embeddings is quite large. The `test_words` list below contains a few new words (called neologisms) and biomedical domain-specific abbreviations. Write code to check whether `glove_wiki_vectors` have representation for these words or not. 
> If a given word `word` is in the vocabulary, `word in glove_wiki_vectors` will return True.

In [10]:
test_words = [
    "covididiot",
    "fomo",
    "frenemies",
    "anthropause",
    "photobomb",
    "selfie",
    "pxg",  # Abbreviation for pseudoexfoliative glaucoma
    "pacg",  # Abbreviation for primary angle closure glaucoma
    "cct",  # Abbreviation for central corneal thickness
    "escc",  # Abbreviation for esophageal squamous cell carcinoma
]

<div class="alert alert-warning">

Solution_1_3
    
</div>

_Points:_ 2

In [11]:
word_presence_boolean = {}

for word in test_words:
    exists = word in glove_wiki_vectors
    word_presence_boolean[word] = exists
    print(f"'{word}': {'Present' if exists else 'NOT present'}")

'covididiot': NOT present
'fomo': NOT present
'frenemies': Present
'anthropause': NOT present
'photobomb': NOT present
'selfie': NOT present
'pxg': NOT present
'pacg': NOT present
'cct': Present
'escc': Present

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 1.4 Stereotypes and biases in embeddings
rubric={points}

Word vectors contain lots of useful information. But they also contain stereotypes and biases of the texts they were trained on. In the lecture, we saw an example of gender bias in Google News word embeddings. Here we are using pre-trained embeddings trained on Wikipedia data. 

**Your tasks:**

1. Explore whether there are any worrisome biases or stereotypes present in these embeddings by trying out at least 4 examples. You can use the following two methods or other methods of your choice to explore this. 
    - the `analogy` function below which gives word analogies (an example shown below)
    - [similarity](https://radimrehurek.com/gensim/models/keyedvectors.html?highlight=similarity#gensim.models.keyedvectors.KeyedVectors.similarity) or [distance](https://radimrehurek.com/gensim/models/keyedvectors.html?highlight=distance#gensim.models.keyedvectors.KeyedVectors.distances) methods (an example is shown below)

> Note that most of the recent embeddings are de-biased. But you might still observe some biases in them. Also, not all stereotypes present in pre-trained embeddings are necessarily bad. But you should be aware of them when you use them in your models.

In [12]:
def analogy(word1, word2, word3, model=glove_wiki_vectors):
    """
    Returns analogy word using the given model.

    Parameters
    --------------
    word1 : (str)
        word1 in the analogy relation
    word2 : (str)
        word2 in the analogy relation
    word3 : (str)
        word3 in the analogy relation
    model :
        word embedding model

    Returns
    ---------------
        pd.dataframe
    """
    print("%s : %s :: %s : ?" % (word1, word2, word3))
    sim_words = model.most_similar(positive=[word3, word2], negative=[word1])
    return pd.DataFrame(sim_words, columns=["Analogy word", "Score"])

Examples of using analogy to explore biases and stereotypes.

In [13]:
analogy("man", "doctor", "woman")

man : doctor :: woman : ?

  Analogy word     Score
0        nurse  0.773523
1    physician  0.718943
2      doctors  0.682433
3      patient  0.675068
4      dentist  0.672603
5     pregnant  0.664246
6      medical  0.652045
7      nursing  0.645348
8       mother  0.639333
9     hospital  0.638750

In [14]:
glove_wiki_vectors.similarity("aboriginal", "success")

np.float32(0.14283238)

In [15]:
glove_wiki_vectors.similarity("white", "success")

np.float32(0.351824)

<div class="alert alert-warning">

Solution_1_4
    
</div>

_Points:_ 4

In [16]:
glove_wiki_vectors.similarity("asian", "success")

np.float32(0.43093374)

In [17]:
glove_wiki_vectors.similarity("african", "success")

np.float32(0.3853135)

In [18]:
glove_wiki_vectors.similarity("american", "success")

np.float32(0.5265027)

In [19]:
glove_wiki_vectors.similarity("man", "sports")

np.float32(0.39511383)

In [20]:
glove_wiki_vectors.similarity("woman", "sports")

np.float32(0.31453365)

In [21]:
glove_wiki_vectors.similarity("transgender", "sports")

np.float32(0.13890198)

In [22]:
analogy("japan", "sushi", "canada")

japan : sushi :: canada : ?

  Analogy word     Score
0      gourmet  0.665378
1         chef  0.604427
2        chefs  0.604360
3      lobster  0.580306
4      burgers  0.571568
5       bistro  0.569237
6      dessert  0.558202
7   restaurant  0.557543
8      cuisine  0.555857
9        fries  0.553588

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 1.5 Discussion
rubric={points}

**Your tasks:**
1. Discuss your observations from 1.4. Are there any worrisome biases in these embeddings trained on Wikipedia?   
2. Give an example of how using embeddings with biases could cause harm in the real world.

<div class="alert alert-warning">

Solution_1_5
    
</div>

_Points:_ 4

1: I tested three different examples in 1.4. In the first one I wanted to expand on the given example by testing if there are any more biases in embeddings between 'success' and different geographical regions. I found that the model relates America a lot more to success than any other region. This reflects bias as many Wikipedia authors are from North America so the content may bias towards the western world more. The second example I tested was to relate different gender identities to 'sports' and it turns out the model does not relate the word 'transgender' to sports much, suggesting underrepresentation in transgender sports on Wikipedia. The third example I tested was using analogy() on 'japan', 'suhsi', and 'canada' to see if the model defaults to relating Canada with stereotypical foods like poutine and maple syrup. It turns out the model did not do that but it did have 'gourmet' as the top word, which may suggest that Canadian food is often associated with elevated dining on Wikipedia. 

2: AI resume screening tools can cause harm in the real world when ranking resumes from job applicants because the model may underestimate a candidate's qualifications based on biased embeddings with words used in their resume. For example, if a non-male individual applies to a job in a male-dominated field such as software programming, the model may see something like "UBC women's swim team captain" on the resume and automatically rank the application lower. This is because the model may not associate "woman" highly with the job title purely from biases in it's learning source.

<!-- END QUESTION -->

<br><br><br><br>

## Exercise 2: Topic modeling 

The goal of topic modeling is discovering high-level themes in a large collection of texts. 

In this homework, you will explore topics in [the 20 newsgroups text dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_20newsgroups.html) using `scikit-learn`'s `LatentDirichletAllocation` (LDA) model. 

Usually, topic modeling is used for discovering abstract "topics" that occur in a collection of documents when you do not know the actual topics present in the documents. But 20 newsgroups text dataset is labeled with categories (e.g., sports, hardware, religion), and you will be able to cross-check the topics discovered by your model with these available topics. 

The starter code below loads the train and test portion of the data and convert the train portion into a pandas DataFrame. For speed, we will only consider documents with the following 8 categories.

In [23]:
from sklearn.datasets import fetch_20newsgroups

In [24]:
cats = [
    "rec.sport.hockey",
    "rec.sport.baseball",
    "soc.religion.christian",
    "alt.atheism",
    "comp.graphics",
    "comp.windows.x",
    "talk.politics.mideast",
    "talk.politics.guns",
]  # We'll only consider these categories out of 20 categories for speed.

newsgroups_train = fetch_20newsgroups(
    subset="train", remove=("headers", "footers", "quotes"), categories=cats
)
X_news_train, y_news_train = newsgroups_train.data, newsgroups_train.target
df = pd.DataFrame(X_news_train, columns=["text"])
df["target"] = y_news_train
df["target_name"] = [
    newsgroups_train.target_names[target] for target in newsgroups_train.target
]
df

,text,target,target_name
0,"You know, I was reading 18 U.S.C. 922 and some...",6,talk.politics.guns
1,\n\n\nIt's not a bad question: I don't have an...,1,comp.graphics
2,"\nActuallay I don't, but on the other hand I d...",1,comp.graphics
3,"The following problem is really bugging me,\na...",2,comp.windows.x
4,\n\n This is the latest from UPI \n\n For...,7,talk.politics.mideast
...,...,...,...
4558,Hi Everyone ::\n\nI am looking for some soft...,1,comp.graphics
4559,Archive-name: x-faq/part3\nLast-modified: 1993...,2,comp.windows.x
4560,"\nThat's nice, but it doesn't answer the quest...",6,talk.politics.guns
4561,"Hi,\n I just got myself a Gateway 4DX-33V ...",2,comp.windows.x
4562,\n\n[h] \tThe Armenians in Nagarno-Karabagh ar...,7,talk.politics.mideast

In [25]:
newsgroups_train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.windows.x',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast']

<br><br>

<!-- BEGIN QUESTION -->

### 2.1 Preprocessing using [spaCy](https://spacy.io/)
rubric={points}

Preprocessing is a crucial step before carrying out topic modeling and it markedly affects topic modeling results. In this exercise, you'll prepare the data using [spaCy](https://spacy.io/) for topic modeling. 

**Your tasks:** 

- Write code using [spaCy](https://spacy.io/) to preprocess the `text` column in the given dataframe `df` and save the processed text in a new column called `text_pp` within the same dataframe.

If you do not have spaCy in your course environment, you'll have to [install it](https://spacy.io/usage) and download the pretrained model en_core_web_md. 

`python -m spacy download en_core_web_md`


Note that there is no such thing as "perfect" preprocessing. You'll have to make your own judgments and decisions on which tokens are likely to be more informative for the given task. Some common text preprocessing steps for topic modeling include: 
- getting rid of slashes, new-line characters, or any other non-informative characters
- sentence segmentation and tokenization      
- replacing urls, email addresses, or numbers with generic tokens such as "URL",  "EMAIL", "NUM". 
- getting rid of other fairly unique tokens which are not going to help us in topic modeling  
- excluding stopwords and punctuation 
- lemmatization


> Check out [these available attributes](https://spacy.io/api/token#attributes) for `token` in spaCy which might help you with preprocessing. 

> You can also get rid of words with specific POS tags. [Here](https://universaldependencies.org/u/pos/) is the list of part-of-speech tags used in spaCy. 

> You may have to use regex to clean text before passing it to spaCy. Also, you might have to go back and forth between preprocessing in this exercise and and topic modeling in Exercise 2 before finalizing preprocessing steps. 

> Note that preprocessing the corpus might take some time. So here are a couple of suggestions: 1) During the debugging phase, work on a smaller subset of the data. 2) Once you finalize the preprocessing part, you might want to save the preprocessed data in a CSV and work with this CSV so that you don't run the preprocessing part every time you run the notebook.

In [26]:
import spacy
nlp = spacy.load("en_core_web_md", disable=["parser", "ner"])

<div class="alert alert-warning">

Solution_2_1
    
</div>

_Points:_ 8

In [27]:
import re

def preprocess_text_col(doc):
    """
    does the following preprocessing steps to a document:
    - lemmatization
    - removes stopwords, punctuation, and whitespace
    - removes numbers and  symbols
    """

    tokens = [
        token.lemma_.lower() 
        for token in doc 
        if not token.is_stop 
        and not token.is_punct 
        and not token.is_space
        and token.is_alpha  
        and len(token.lemma_) > 2
    ]
    return " ".join(tokens)

def regex_clean(text):
    text = re.sub(r'\S+@\S+', 'EMAIL', text) 
    text = re.sub(r'http\S+', 'URL', text)   
    return text

In [28]:
df['text_pp'] = [
    preprocess_text_col(doc) 
    for doc in nlp.pipe(df['text'].apply(regex_clean), batch_size=500)
]

In [29]:
df.iloc[2:6]

,text,target,target_name,text_pp
2,"\nActuallay I don't, but on the other hand I d...",1,comp.graphics,actuallay hand support idea have newsgroup asp...
3,"The following problem is really bugging me,\na...",2,comp.windows.x,follow problem bug appreciate help create wind...
4,\n\n This is the latest from UPI \n\n For...,7,talk.politics.mideast,late upi foreign ministry spokesman ferhat ata...
5,"Hi,\n I'd like to subscribe to Leadership Ma...",5,soc.religion.christian,like subscribe leadership magazine wonder disk...

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 2.2 Build a topic model using sklearn's LatentDirichletAllocation
rubric={points}

**Your tasks:**

1. Build LDA models on the preprocessed data using using [sklearn's `LatentDirichletAllocation`](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html) and random state 42. Experiment with a few values for the number of topics (`n_components`). Pick a reasonable number for the number of topics and briefly justify your choice.

<div class="alert alert-warning">

Solution_2_2
    
</div>

_Points:_ 4

_Type your answer here, replacing this text._

In [30]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer(stop_words='english', max_features=10000, min_df=2)
X = vec.fit_transform(df['text_pp'])

n_topics = 6
lda = LatentDirichletAllocation(
    n_components=n_topics, learning_method="batch", max_iter=10, random_state=42
)

lda.fit(X)

LatentDirichletAllocation(n_components=6, random_state=42)

In [31]:
sorting = np.argsort(lda.components_, axis=1)[:, ::-1]
feature_names = np.array(vec.get_feature_names_out())

import mglearn

mglearn.tools.print_topics(
    topics=range(6),
    feature_names=feature_names,
    sorting=sorting,
    topics_per_chunk=6,
    n_words=10,
)

topic 0       topic 1       topic 2       topic 3       topic 4       topic 5
--------      --------      --------      --------      --------      --------
god           know          gun           game          armenian      email
people        say           law           team          israel        file
believe       think         weapon        play          turkish       program
jesus         people        people        year          jews          use
think         come          right         player        people        image
know          like          state         good          armenians     window
question      time          government    win           israeli       available
church        tell          firearm       season        turkey        include
thing         thing         crime         hockey        war           run
say           want          control       league        kill          server

I picked 6 for the number of topics. I started off with 10 topics since there are 20 news groups and I thought picking half the number as n_components is a safe baseline to start from. I noticed there were topics with the same words and some topics contained words that did not seem to relate to each other. I believed this problem was due to having too many topics so I gradually decreased n_components 1 at a time until I reached n_components = 6, which then the problem stopped occurring.

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 2.3 Exploring word topic association
rubric={points}

**Your tasks:**
1. For the number of topics you picked in the previous exercise, show top 10 words for each of your topics and suggest labels for each of the topics (similar to how we came up with labels "health and nutrition", "fashion", and "machine learning" in the toy example we saw in class). 

> If your topics do not make much sense, you might have to go back to preprocessing in Exercise 2.1, improve it, and train your LDA model again.

<div class="alert alert-warning">

Solution_2_3
    
</div>

_Points:_ 5

In [32]:
mglearn.tools.print_topics(
    topics=range(6),
    feature_names=feature_names,
    sorting=sorting,
    topics_per_chunk=6,
    n_words=10,
)

topic 0       topic 1       topic 2       topic 3       topic 4       topic 5
--------      --------      --------      --------      --------      --------
god           know          gun           game          armenian      email
people        say           law           team          israel        file
believe       think         weapon        play          turkish       program
jesus         people        people        year          jews          use
think         come          right         player        people        image
know          like          state         good          armenians     window
question      time          government    win           israeli       available
church        tell          firearm       season        turkey        include
thing         thing         crime         hockey        war           run
say           want          control       league        kill          server

topic 0 = religion  
topic 1 = verbs  
topic 2 = firearm politics  
topic 3 = sports  
topic 4 = current conflicts  
topic 5 = software  

Note: I already accidentally did this step in part 2.2 so I pasted the appropriate code over.

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 2.4 Exploring document topic association
rubric={points}

**Your tasks:**
1. Show the document topic assignment of the first five documents from `df`.

<div class="alert alert-warning">

Solution_2_4
    
</div>

_Points:_ 5

In [33]:
document_topics = lda.transform(X)

results = pd.DataFrame(
    document_topics[:5], 
    columns=[f"Topic {i}" for i in range(n_topics)],
    index=[f"Doc {i}" for i in range(5)]
)

results['Highest_Topic'] = results.idxmax(axis=1)

print("Topic probabilities and assignments for the first five documents:")
display(results)

Topic probabilities and assignments for the first five documents:

,Topic 0,Topic 1,Topic 2,Topic 3,Topic 4,Topic 5,Highest_Topic
Doc 0,0.080950,0.176903,0.732086,0.003345,0.003353,0.003363,Topic 2
Doc 1,0.002435,0.350165,0.002426,0.002434,0.002434,0.640106,Topic 5
Doc 2,0.262947,0.388175,0.003429,0.003421,0.003419,0.338609,Topic 1
Doc 3,0.008027,0.152792,0.007987,0.007953,0.007991,0.815249,Topic 5
Doc 4,0.004299,0.004296,0.047335,0.004295,0.935482,0.004293,Topic 4

<!-- END QUESTION -->

<br><br><br><br>

<!-- BEGIN QUESTION -->

## Exercise 3: Short answer questions 
<hr>

rubric={points}

1. Briefly explain how content-based filtering works in the context of recommender systems. 
2. Discuss at least two negative consequences of recommender systems.
3. What is transfer learning in natural language processing? Briefly explain.

<div class="alert alert-warning">

Solution_3
    
</div>

_Points:_ 6

1: The model builds a profile of features for each item, and a profile of previously liked items for each user. Then, the model will recommend new items to the user that have similar features to the items previously liked by said user. 

2: One negative consequence is the emergence of filter bubbles, meaning the recommender system starts to only show content the user already aligns with. This can limit exposure to other viewpoints and build bias. Another consequence is privacy concerns as the line between data needed for the model to work effectively and users' private information can become blurry. Large social media companies such as Facebook has faced controversy before for collecting private user info to drive personalized ad recommendations. 

3: Transfer learning in NLP means using a pre-trained model as the starting point for training a new model. For example, someone can use a model already trained on the vocabulary from certain sources and fine tune it on a more specific dataset to suit their needs.

<!-- END QUESTION -->

<br><br><br><br>

Before submitting your assignment, please make sure you have followed all the instructions in the Submission Instructions section at the top. 

Here is a quick checklist before submitting: 

- [ ] Restart kernel, clear outputs, and run all cells from top to bottom.  
- [ ] `.ipynb` file runs without errors and contains all outputs.  
- [ ] Only `.ipynb` and required output files are uploaded (no extra files).  
- [ ] Execution numbers start at **1** and are in order.  
- [ ] If `.ipynb` is too large and doesn't render on Gradescope, also upload a PDF/HTML version.  
- [ ] Reviewed the [CPSC 330 homework instructions](https://ubc-cs.github.io/cpsc330-2025W2/docs/homework-instructions).

![](img/eva-well-done.png)